// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multiplayer_Strategy_Game_Website_API.Data;

#nullable disable

namespace Multiplayer_Strategy_Game_Website_API.Migrations
{
    [DbContext(typeof(GameSiteDbContext))]
    [Migration("20260329032702_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Multiplayer_Strategy_Game_Website_API.Models.Game", b =>
                {
                    b.Property<int>("gameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gameId"));

                    b.Property<string>("gameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gameStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("gameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            gameId = 1,
                            gameName = "TicTacToe",
                            gameStatus = "Testing"
                        },
                        new
                        {
                            gameId = 2,
                            gameName = "Connect 4",
                            gameStatus = "Testing"
                        },
                        new
                        {
                            gameId = 3,
                            gameName = "Connect The Dots",
                            gameStatus = "Closed"
                        });
                });

            modelBuilder.Entity("Multiplayer_Strategy_Game_Website_API.Models.Lobby", b =>
                {
                    b.Property<int>("lobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lobbyId"));

                    b.Property<int?>("lobbyChallengerId")
                        .HasColumnType("int");

                    b.Property<string>("lobbyChallengerStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("lobbyDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("lobbyGameId")
                        .HasColumnType("int");

                    b.Property<int>("lobbyHostID")
                        .HasColumnType("int");

                    b.Property<string>("lobbyHostStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lobbyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lobbyVisibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lobbyId");

                    b.ToTable("Lobbies");

                    b.HasData(
                        new
                        {
                            lobbyId = 1,
                            lobbyChallengerId = 2,
                            lobbyChallengerStatus = "won",
                            lobbyDateCreated = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lobbyGameId = 1,
                            lobbyHostID = 1,
                            lobbyHostStatus = "lost",
                            lobbyStatus = "closed",
                            lobbyVisibility = "public"
                        },
                        new
                        {
                            lobbyId = 2,
                            lobbyChallengerId = 3,
                            lobbyChallengerStatus = "won",
                            lobbyDateCreated = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lobbyGameId = 2,
                            lobbyHostID = 2,
                            lobbyHostStatus = "lost",
                            lobbyStatus = "closed",
                            lobbyVisibility = "private"
                        },
                        new
                        {
                            lobbyId = 3,
                            lobbyDateCreated = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lobbyGameId = 1,
                            lobbyHostID = 1,
                            lobbyStatus = "Open",
                            lobbyVisibility = "public"
                        });
                });

            modelBuilder.Entity("Multiplayer_Strategy_Game_Website_API.Models.Player", b =>
                {
                    b.Property<int>("playerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("playerId"));

                    b.Property<DateTime>("playerDateJoined")
                        .HasColumnType("datetime2");

                    b.Property<string>("playerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("playerPasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("playerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            playerId = 1,
                            playerDateJoined = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            playerName = "techstreet",
                            playerPasswordHash = "XohImNooBHFR0OVvjcYpJ3NgPQ1qq73WKhHvch0VQtg="
                        },
                        new
                        {
                            playerId = 2,
                            playerDateJoined = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            playerName = "progamer97",
                            playerPasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI="
                        },
                        new
                        {
                            playerId = 3,
                            playerDateJoined = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            playerName = "GameSkayer93",
                            playerPasswordHash = "ZehL4zUy+3hMSBKWdfnv86aCsnFowOp0Syz1juAjN8U="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
